language: php

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.3
      env: COVERALLS_VERSION='^2.0'
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' COVERALLS_VERSION='^2.0'
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - if [[ -z "$COVERALLS_VERSION" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
  - composer self-update
  - if [[ -n "$COVERALLS_VERSION" ]]; then composer require php-coveralls/php-coveralls:${COVERALLS_VERSION}; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

before_script:
- if [[ -n "$COVERALLS_VERSION" ]]; then mkdir -p coverage; fi

script:
  - if [[ -n "$COVERALLS_VERSION" ]]; then vendor/bin/phpunit --verbose --coverage-clover=coverage/clover.xml; else vendor/bin/phpunit --verbose; fi

after_success:
  - if [[ -n "$COVERALLS_VERSION" ]]; then php vendor/bin/php-coveralls -v -x coverage/clover.xml; fi
